export const PIECE_OF_SCROLL = [
  {
    type: "weapon",
    values: [
      {
        level: 70,
        reinforce_stat: [
          {
            percent: 100,
            up_attack_power: 1,
            up_magic_power: 1,
            up_stat: 0,
            up_hp: 0,
          },
          {
            percent: 70,
            up_attack_power: 2,
            up_magic_power: 2,
            up_stat: 0,
            up_hp: 0,
          },
          {
            percent: 30,
            up_attack_power: 3,
            up_magic_power: 3,
            up_stat: 1,
            up_hp: 50,
          },
          {
            percent: 15,
            up_attack_power: 5,
            up_magic_power: 5,
            up_stat: 2,
            up_hp: 100,
          },
        ],
      },
      {
        level: 110,
        reinforce_stat: [
          {
            percent: 100,
            up_attack_power: 2,
            up_magic_power: 2,
            up_stat: 0,
            up_hp: 0,
          },
          {
            percent: 70,
            up_attack_power: 3,
            up_magic_power: 3,
            up_stat: 1,
            up_hp: 50,
          },
          {
            percent: 30,
            up_attack_power: 5,
            up_magic_power: 5,
            up_stat: 2,
            up_hp: 100,
          },
          {
            percent: 15,
            up_attack_power: 7,
            up_magic_power: 7,
            up_stat: 3,
            up_hp: 150,
          },
        ],
      },
      {
        level: 250,
        reinforce_stat: [
          {
            percent: 100,
            up_attack_power: 3,
            up_magic_power: 3,
            up_stat: 1,
            up_hp: 50,
          },
          {
            percent: 70,
            up_attack_power: 5,
            up_magic_power: 5,
            up_stat: 2,
            up_hp: 100,
          },
          {
            percent: 30,
            up_attack_power: 7,
            up_magic_power: 7,
            up_stat: 3,
            up_hp: 150,
          },
          {
            percent: 15,
            up_attack_power: 9,
            up_magic_power: 9,
            up_stat: 4,
            up_hp: 200,
          },
        ],
      },
    ],
  },
  {
    type: "armor",
    values: [
      {
        level: 70,
        reinforce_stat: [
          {
            percent: 100,
            up_attack_power: 0,
            up_magic_power: 0,
            up_stat: 1,
            up_all_stat: 0,
            up_hp: 5,
            up_demon_hp: 55,
            up_armor: 1,
          },
          {
            percent: 70,
            up_attack_power: 0,
            up_magic_power: 0,
            up_stat: 2,
            up_all_stat: 0,
            up_hp: 15,
            up_demon_hp: 115,
            up_armor: 2,
          },
          {
            percent: 30,
            up_attack_power: 0,
            up_magic_power: 0,
            up_stat: 3,
            up_all_stat: 1,
            up_hp: 30,
            up_demon_hp: 180,
            up_armor: 4,
          },
          {
            percent: 15,
            up_attack_power: 0,
            up_magic_power: 0,
            up_stat: 4,
            up_all_stat: 2,
            up_hp: 45,
            up_demon_hp: 245,
            up_armor: 6,
          },
        ],
      },
      {
        level: 115,
        reinforce_stat: [
          {
            percent: 100,
            up_attack_power: 0,
            up_magic_power: 0,
            up_stat: 2,
            up_all_stat: 0,
            up_hp: 20,
            up_demon_hp: 120,
            up_armor: 2,
          },
          {
            percent: 70,
            up_attack_power: 0,
            up_magic_power: 0,
            up_stat: 3,
            up_all_stat: 0,
            up_hp: 40,
            up_demon_hp: 190,
            up_armor: 4,
          },
          {
            percent: 30,
            up_attack_power: 0,
            up_magic_power: 0,
            up_stat: 5,
            up_all_stat: 2,
            up_hp: 70,
            up_demon_hp: 320,
            up_armor: 7,
          },
          {
            percent: 15,
            up_attack_power: 0,
            up_magic_power: 0,
            up_stat: 7,
            up_hp: 110,
            up_demon_hp: 460,
            up_all_stat: 3,
            up_armor: 10,
          },
        ],
      },
      {
        level: 250,
        reinforce_stat: [
          {
            percent: 100,
            up_attack_power: 0,
            up_magic_power: 0,
            up_stat: 3,
            up_hp: 30,
            up_demon_hp: 120,
            up_all_stat: 0,
            up_armor: 3,
          },
          {
            percent: 70,
            up_attack_power: 0,
            up_magic_power: 0,
            up_stat: 4,
            up_hp: 70,
            up_demon_hp: 270,
            up_all_stat: 0,
            up_armor: 5,
          },
          {
            percent: 30,
            up_attack_power: 0,
            up_magic_power: 0,
            up_stat: 7,
            up_hp: 120,
            up_demon_hp: 470,
            up_all_stat: 3,
            up_armor: 10,
          },
          {
            percent: 15,
            up_attack_power: 0,
            up_magic_power: 0,
            up_stat: 10,
            up_hp: 170,
            up_demon_hp: 670,
            up_all_stat: 4,
            up_armor: 15,
          },
        ],
      },
    ],
  },
  {
    type: "glove",
    values: [
      {
        level: 70,
        reinforce_stat: [
          {
            percent: 100,
            up_attack_power: 0,
            up_magic_power: 0,
            up_armor: 3,
          },
          {
            percent: 70,
            up_attack_power: 1,
            up_magic_power: 1,
            up_armor: 0,
          },
          {
            percent: 30,
            up_attack_power: 2,
            up_magic_power: 2,
            up_armor: 0,
          },
          {
            percent: 15,
            up_attack_power: 3,
            up_magic_power: 3,
            up_armor: 0,
          },
        ],
      },
      {
        level: 200,
        reinforce_stat: [
          {
            percent: 100,
            up_attack_power: 1,
            up_magic_power: 1,
            up_armor: 0,
          },
          {
            percent: 70,
            up_attack_power: 2,
            up_magic_power: 2,
            up_armor: 0,
          },
          {
            percent: 30,
            up_attack_power: 3,
            up_magic_power: 3,
            up_armor: 0,
          },
          {
            percent: 15,
            up_attack_power: 4,
            up_magic_power: 4,
            up_armor: 0,
          },
        ],
      },
    ],
  },
  {
    type: "accessory",
    values: [
      {
        level: 70,
        reinforce_stat: [
          {
            percent: 100,
            up_attack_power: 0,
            up_magic_power: 0,
            up_stat: 1,
            up_hp: 50,
            up_all_stat: 0,
          },
          {
            percent: 70,
            up_attack_power: 0,
            up_magic_power: 0,
            up_stat: 2,
            up_hp: 100,
            up_all_stat: 0,
          },
          {
            percent: 30,
            up_attack_power: 0,
            up_magic_power: 0,
            up_stat: 3,
            up_hp: 150,
            up_all_stat: 1,
          },
        ],
      },
      {
        level: 115,
        reinforce_stat: [
          {
            percent: 100,
            up_attack_power: 0,
            up_magic_power: 0,
            up_stat: 1,
            up_hp: 50,
            up_all_stat: 0,
          },
          {
            percent: 70,
            up_attack_power: 0,
            up_magic_power: 0,
            up_stat: 2,
            up_hp: 100,
            up_all_stat: 0,
          },
          {
            percent: 30,
            up_attack_power: 0,
            up_magic_power: 0,
            up_stat: 4,
            up_hp: 200,
            up_all_stat: 2,
          },
        ],
      },
      {
        level: 200,
        reinforce_stat: [
          {
            percent: 100,
            up_attack_power: 0,
            up_magic_power: 0,
            up_stat: 2,
            up_hp: 100,
            up_all_stat: 0,
          },
          {
            percent: 70,
            up_attack_power: 0,
            up_magic_power: 0,
            up_stat: 3,
            up_hp: 150,
            up_all_stat: 0,
          },
          {
            percent: 30,
            up_attack_power: 0,
            up_magic_power: 0,
            up_stat: 5,
            up_hp: 250,
            up_all_stat: 3,
          },
        ],
      },
    ],
  },
  {
    type: "heart",
    values: [
      {
        level: 30,
        reinforce_stat: [
          {
            percent: 100,
            up_attack_power: 1,
            up_magic_power: 1,
            up_stat: 0,
            up_hp: 0,
            up_all_stat: 0,
          },
          {
            percent: 70,
            up_attack_power: 2,
            up_magic_power: 2,
            up_stat: 0,
            up_hp: 0,
            up_all_stat: 0,
          },
          {
            percent: 30,
            up_attack_power: 3,
            up_magic_power: 3,
            up_stat: 0,
            up_hp: 0,
            up_all_stat: 0,
          },
        ],
      },
      {
        level: 200,
        reinforce_stat: [
          {
            percent: 100,
            up_attack_power: 2,
            up_magic_power: 2,
            up_stat: 0,
            up_hp: 0,
            up_all_stat: 0,
          },
          {
            percent: 70,
            up_attack_power: 3,
            up_magic_power: 3,
            up_stat: 0,
            up_hp: 0,
            up_all_stat: 0,
          },
          {
            percent: 30,
            up_attack_power: 5,
            up_magic_power: 5,
            up_stat: 0,
            up_hp: 0,
            up_all_stat: 0,
          },
        ],
      },
    ],
  },
];
