import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";
import Myheader from "@/components/Myheader";
import { GoogleAnalytics } from "@next/third-parties/google";

const myFont = localFont({
  src: "./NEXON Lv1 Gothic OTF.otf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Maple prism",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <meta name="theme-color" content="#3D39F1" />
      <link rel="manifest" href="/manifest.json" />
      <body className={myFont.className}>
        <Providers>
          <div className="max-h-screen">
            <Myheader />
            {children}
          </div>
        </Providers>
      </body>
      <GoogleAnalytics gaId="G-LV519XYDT1" />
    </html>
  );
}
